---
- name: Archlinux post install
  hosts: localhost
  become: yes

  tasks:
    - name: base-devel
      package:
        name: base-devel
        state: present

    - name: curl
      package:
        name: curl
        state: present

    - name: Ghostty
      package:
        name: ghostty
        state: present

    - name: Neovim
      package:
        name: neovim
        state: present

    - name: xclip
      package:
        name: xclip
        state: present

    - name: Steam # very important
      package:
        name: steam
        state: present
