---
- hosts: localhost

- name: Arch post install
  import_playbook: tasks/arch_post_install.yml

- name: AUR installs
  import_playbook: tasks/aur.yml

- name: Python setup
  import_playbook: tasks/python.yml

- name: Dev setup
  import_playbook: tasks/dev.yml
